# Generated by Django 5.2.3 on 2025-06-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('mood', models.CharField(choices=[('happy', '😁 Happy'), ('sad', '😞 Sad'), ('tired', '😪 Tired'), ('stressed', '😰 Stressed'), ('love', '🥰 In Love')], max_length=20)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
