# Generated by Django 5.2.3 on 2025-06-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
