# Generated by Django 5.2.3 on 2025-06-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_music_artist_alter_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('love', 'In Love')], max_length=20),
        ),
    ]
