# Generated by Django 5.2.3 on 2025-07-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermood',
            name='mood_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
